-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvtlFK1SWMV5pfMZFIEM5m1XE2GNREQkImAphyecSh/qgCgYIKoZIzj0DAQehRANCAASxu2nWT/QMRY6n0moKRbgjITdzVWiavg6TY2JqQ6JPiXuHbxobbPawcLIeH8z11tLVOzG6FE1QDs1s9rP8yRh/
-----END PRIVATE KEY-----